### ISSUE TITLE
Make library go-gettable

### ISSUE THREAD

**Issue by timshannon** [rhinoman/go-commonmark#1]
It would be fantastic if this could be bundled statically and built with go like out https://github.com/mattn/go-sqlite3 does it.

Since it's a pure-C library it should be possible.

**Comment by timshannon** [comment]
FYI, I forked your library and messed with it a bit, and was able to get it to work:

https://github.com/timshannon/go-commonmark/

Merge if you want, otherwise my fork suites my purposes for now.

Thanks,

**Comment by rhinoman** [comment]
Thanks, I like the idea.  I'll take a look at this later tonight.

**Comment by rhinoman** [comment]
I checked out your fork and haven't been able to get it to run correctly (I removed my installed libcmark to make sure it wasn't linking that in, which it will do).  Running 'go test' throws an error about the missing cmark library.  What's your build procedure?

**Comment by timshannon** [comment]
Just go get works for me. Not sure what the issue is.   I'll try it later
on a fresh install.

**Comment by timshannon** [comment]
Just confirmed on a a fresh install of Ubuntu.  Installed go, then did go get github.com/timshannon/go-commonmark and it installed fine.

Are you trying against your own repository?  There were several things I needed to change in order to get it build properly with the go compiler.

**Comment by rhinoman** [comment]
Figured it out.  commonmark_test.go in your fork was still importing go-commonmark from my repo :)

**Comment by rhinoman** [comment]
@timshannon, I'll merge this in --  go ahead and submit a pull request.

**Comment by timshannon** [comment]
Looks like you merged my change already and reverted it.  I'll create a brand new repository / pull request so it can be merged properly.

**Comment by rhinoman** [comment]
Merged it in.  Thanks.
