### ISSUE TITLE
Expose escape_html and escape_href as go functions

### ISSUE THREAD

**Issue by rabidgremlin** [rhinoman/go-commonmark#6]
It would be great if the *escape_html* and *escape_href* functions in *html.c* could be exposed as go functions that accepted and returned strings.

The commonmark escaping is non-standard and a pain to implement :)

**Comment by rhinoman** [comment]
I suppose it would be possible to create wrappers for them.  However, those don't appear to be functions exported from libcmark (they look like internal functions to me).  Though, I'm a little curious, what would you use them for?

**Comment by rabidgremlin** [comment]
I'm creating a small package that processes the AST generated by libcmark so that you can create "pluggable" outputs (eg something other then HTML). My first one is an HTML generator that I testing against the spec to make sure everything works as expected.

Unfortunately the commonmark escape functions are non-standard in a few places so cannot be replicated without a good deal of hackery which I can avoid if I use the ones in libcmark.

**Comment by rhinoman** [comment]
On closer inspection, I realized those two functions are static (not easily wrappable), and I'd rather not start editing core libcmark files to work around that (it gives me more things I'd have to maintain in go-commonmark).  However, the two functions just turn around and call houdini: https://github.com/vmg/houdini.  Creating a Go wrapper for the houdini library is probably beyond the scope of go-commonmark.  I'd recommend just bringing houdini into your project and wrapping the functions you need.

**Comment by rabidgremlin** [comment]
Fair enough, I agree you don't want to mess with the core libcmark. I'll see if I can wrap houdini myself. Thanks
