### ISSUE TITLE
GFM extensions?

### ISSUE THREAD

**Issue by justinclift** [rhinoman/go-commonmark#8]
Recently started using go-commonmark as a quick way to enable Markdown handling for an experimental project being worked on.

Starting to miss the GitHub Flavoured Markdown extensions (specifically, tables at the moment).

If someone submits a PR updating cmark (prob to 0.27.1), and also including the GFM extensions, is it likely to be accepted?  Assuming reasonable code quality of course. :wink:

**Comment by rhinoman** [comment]
Yes,  I'd definitely accept a PR.  Thanks!

-James

**Comment by justinclift** [comment]
Finally got around to look at the GFM state of things, and it turned out there's a [different project already](https://github.com/shurcooL/github_flavored_markdown) which does 99.9% of what we need, so went with that instead.

Thanks for the time you put into go-commonmark @rhinoman, it helped us get up and running quickly. :smile:
